name: verdicci
version: 0.0.1
dependencies:
  browser: any
  angular: 0.14.0
  polymer: ">=0.14.0+1 <0.15.0"
  core_elements: ">=0.2.1+1 <0.3.0"
  paper_elements:  ">=0.2.0 <0.3.0"
dependency_overrides:
  args: ">=0.11.0 <0.13.0"
  code_transformers: ">=0.2.3 <0.3.0"
  html5lib: ">=0.12.0 <0.13.0"
transformers:
- angular
- polymer