name: verdicci
version: 0.0.1
dependencies:
  browser: any
  polymer: "0.14.3"
  core_elements: "0.2.2+1"
  paper_elements:  "0.3.0+1"
  angular: "0.14.0"
dependency_overrides:
  args: "0.11.0"
  code_transformers: "0.2.3+1"
  html5lib: "0.12.0"
transformers:
- angular:
    html_files:
      - view/welcome_view.html
